version: '3.7'

services:   
# -------- mogoDB -------- #  
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: gift923
    ports:
      - 28017:27017
    volumes:
      - ./mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: gift923
      ME_CONFIG_MONGODB_URL: mongodb://root:gift923@mongo:27017/

# -------- nginx + frontend -------- # 
  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend:/www/data/
    ports:
      - 8080:80
    depends_on:
      - api

# -------- API -------- # 
