version: '3.7'

services:   
# -------- postgres database -------- #  
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: frog135
      POSTGRES_USER: admin
    ports:
      - 5431:5432
    volumes:
      - ./db/data/:/var/lib/postgresql/data/

# -------- nginx + frontend -------- # 
  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend:/www/data/
    ports:
      - 8080:80
    depends_on:
      - api

# -------- API -------- # 
  admin-api:
    build: 
      context: ./api
      dockerfile: ./Dockerfile
    depends_on:
      - db
    volumes:
      - ./api/appsettings.json:/api/appsettings.json
    ports:
      - 8081:80
